uint8 value

uint8 UNKNOWN=0   # Unknown
uint8 DRIVE01=1   #  1st (Drive)
uint8 DRIVE02=2   #  2nd (Drive)
uint8 DRIVE03=3   #  3rd (Drive)
uint8 DRIVE04=4   #  4th (Drive)
uint8 DRIVE05=5   #  5th (Drive)
uint8 DRIVE06=6   #  6th (Drive)
uint8 DRIVE07=7   #  7th (Drive)
uint8 DRIVE08=8   #  8th (Drive)
uint8 DRIVE09=9   #  9th (Drive)
uint8 DRIVE10=10  # 10th (Drive)
uint8 REVERSE1=11 # 1st (Reverse)
uint8 REVERSE2=12 # 2nd (Reverse)
uint8 NEUTRAL=14  # Neutral (N)
uint8 PARK=15     # Park (P)
