std_msgs/Header header

# Front Driver Temperature Status
FrontTemp ft_drv_temp

# Front Passenger Temperature Status
FrontTemp ft_psg_temp

# Front Fan Speed Status
FrontFanSpeed ft_fan_speed

# Front Button Status
bool max_ac
bool ac
bool ft_hvac
bool auto_md
bool recirc
bool sync
bool r_defr
bool f_defr

# Vent Mode Status
VentMode vent_mode

# Heated Steering Wheel Status
bool heated_steering_wheel

# Front Left Heated Seat Status
HvacSeat fl_heated_seat

# Front Left Vented Seat Status
HvacSeat fl_vented_seat

# Front Right Heated Seat Status
HvacSeat fr_heated_seat

# Front Right Vented Seat Status
HvacSeat fr_vented_seat
