std_msgs/Header header

# Turn signal command enumeration
TurnSignal cmd

# Door open/close command
DoorCmd door

# Front Driver Temperature Command
FrontTemp ft_drv_temp

# Front Passenger Temperature Command
FrontTemp ft_psg_temp

# Front Fan Speed Command
FrontFanSpeed ft_fan_speed

# Front Button Command
HvacButtonCmd max_ac
HvacButtonCmd ac
HvacButtonCmd ft_hvac
HvacButtonCmd auto_md
HvacButtonCmd recirc
HvacButtonCmd sync
HvacButtonCmd r_defr
HvacButtonCmd f_defr

# Front Vent Mode Command
VentMode vent_mode

# Heated Steering Wheel Command
HvacButtonCmd heated_steering_wheel

# Front Left Heated Seat Command
HvacSeat fl_heated_seat

# Front Left Vented Seat Command
HvacSeat fl_vented_seat

# Front Right Heated Seat Command
HvacSeat fr_heated_seat

# Front Right Vented Seat Command
HvacSeat fr_vented_seat
